//
// Generated file, do not edit! Created by opp_msgc 4.2 from networklayer/contract/IPv6ControlInfo_hacked.msg.
//

#ifndef _IPV6CONTROLINFO_HACKED_M_H_
#define _IPV6CONTROLINFO_HACKED_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "IPv6ControlInfo.h"
#include "SCADASIMDefs.h"
// }}



/**
 * Class generated from <tt>networklayer/contract/IPv6ControlInfo_hacked.msg</tt> by opp_msgc.
 * <pre>
 * class IPv6ControlInfo_hacked extends IPv6ControlInfo
 * {
 * 	
 * 	short attackTag = 0;
 * }
 * </pre>
 */
class IPv6ControlInfo_hacked : public ::IPv6ControlInfo
{
  protected:
    short attackTag_var;

  private:
    void copy(const IPv6ControlInfo_hacked& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const IPv6ControlInfo_hacked&);

  public:
    IPv6ControlInfo_hacked();
    IPv6ControlInfo_hacked(const IPv6ControlInfo_hacked& other);
    virtual ~IPv6ControlInfo_hacked();
    IPv6ControlInfo_hacked& operator=(const IPv6ControlInfo_hacked& other);
    virtual IPv6ControlInfo_hacked *dup() const {return new IPv6ControlInfo_hacked(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual short getAttackTag() const;
    virtual void setAttackTag(short attackTag);
};

inline void doPacking(cCommBuffer *b, IPv6ControlInfo_hacked& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, IPv6ControlInfo_hacked& obj) {obj.parsimUnpack(b);}


#endif // _IPV6CONTROLINFO_HACKED_M_H_
